### ISSUE TITLE
small typo in docs

### ISSUE THREAD

**Issue by nic-Oban** [mlesnoff/JchemoDemo#3]
Hey Matthieu,
you have a small typo there:
https://github.com/mlesnoff/JchemoDemo/blob/d56cc80baaca26040eb66b4f42b5745038ec48d2/docs/src/assets/html/Regression/gridscore_lwplsr_tecator.html#L6

The page title is "gridcv" but it actually should be "gridscore" ;) 
Have a good day!
Nicolas

**Comment by mlesnoff** [comment]
Hi Nicolas, you are right, I corrected. Thanks!
